apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: conservation-canid-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: conservation-canid-nodejs 
  name: conservation-canid-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: conservation-canid-nodejs 
